export type ThemeTier = "basic" | "luxe" | "signature";
export type ThemeFamily = "floral" | "royal" | "editorial" | "destination" | "festive" | "traditional" | "dramatic" | "romantic";

export type PortfolioTheme = {
  slug: string;
  name: string;
  tagline: string;
  shortDescription: string;
  couple: string;
  location: string;
  palette: string[];
  image: string;
  accent: string;
  background: string;
  tier: ThemeTier;
  category: string;
  family: ThemeFamily;
  badge?: string;
  layoutStyle?: string;
  motionStyle?: string;
  typographyStyle?: string;
};

export const BRAND = {
  name: "The Digital Inviters",
  tagline: "Boutique digital wedding invitations, crafted with love",
  whatsappNumber: "917240345334",
  whatsappBase: "https://wa.me/917240345334?text=",
  upiId: "abhishekprajapatiad-1@okhdfcbank",
};

export const PORTFOLIO_THEMES: PortfolioTheme[] = [
  // ═══════════════════════════════════════════
  //  SIGNATURE / BESPOKE — Ultra-premium showcase
  // ═══════════════════════════════════════════
  {
    slug: "palace-heirloom",
    name: "Palace Heirloom",
    tagline: "An invitation worthy of royalty.",
    shortDescription: "Hand-illustrated Mughal motifs, real gold leaf textures, cinematic parallax storytelling, and a presentation that feels like holding a royal decree. For weddings where only extraordinary will do.",
    couple: "Maharani Padmini & Prince Vikram",
    location: "Udaipur, Rajasthan",
    palette: ["#0d0907", "#c9a14a", "#7a1f2b", "#fdf4e3"],
    image: "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=1200&q=90",
    accent: "#c9a14a",
    background: "#0d0907",
    tier: "signature",
    category: "Royal",
    family: "royal",
    badge: "Bespoke",
    layoutStyle: "cinematic-scroll",
    motionStyle: "parallax-gold",
    typographyStyle: "serif-regal",
  },
  {
    slug: "midnight-symphony",
    name: "Midnight Symphony",
    tagline: "Where darkness meets devotion.",
    shortDescription: "Deep midnight blues, constellation maps, and orchestral motion — a cinematic night-sky experience with immersive scroll storytelling and atmospheric sound design.",
    couple: "Aria & Sebastian",
    location: "Jodhpur, Rajasthan",
    palette: ["#0a0e1a", "#1a2744", "#c9a87c", "#e8ddd0"],
    image: "https://images.unsplash.com/photo-1507400492013-162706c8c05e?auto=format&fit=crop&w=1200&q=90",
    accent: "#c9a87c",
    background: "#0a0e1a",
    tier: "signature",
    category: "Dramatic",
    family: "dramatic",
    badge: "Bespoke",
    layoutStyle: "immersive-fullscreen",
    motionStyle: "constellation-drift",
    typographyStyle: "display-cinematic",
  },
  {
    slug: "eternal-rose-house",
    name: "Eternal Rose House",
    tagline: "A love letter in bloom.",
    shortDescription: "Hand-painted botanical illustrations, velvet textures, editorial typography, and museum-quality art direction — an invitation that belongs in a gallery.",
    couple: "Adeline & Hugo",
    location: "Paris, France",
    palette: ["#faf5f2", "#8b3a4a", "#c9a14a", "#2c1810"],
    image: "https://images.unsplash.com/photo-1490750967868-88aa4f44bacd?auto=format&fit=crop&w=1200&q=90",
    accent: "#8b3a4a",
    background: "#faf5f2",
    tier: "signature",
    category: "Romantic",
    family: "romantic",
    badge: "Bespoke",
    layoutStyle: "editorial-gallery",
    motionStyle: "petal-float",
    typographyStyle: "serif-botanical",
  },

  // ═══════════════════════════════════════════
  //  LUXE — Cinematic, immersive, emotional
  // ═══════════════════════════════════════════
  {
    slug: "royal-palace",
    name: "Royal Palace",
    tagline: "Timeless elegance for an unforgettable wedding.",
    shortDescription: "Opulent Rajasthani palace invite with gold leaf accents, rich maroon, cinematic parallax scroll, background music, and regal warmth that transports your guests into a royal celebration.",
    couple: "Ananya & Veer",
    location: "Jaipur, Rajasthan",
    palette: ["#fdf4e3", "#c9a14a", "#7a1f2b", "#2a0a12"],
    image: "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=1200&q=85",
    accent: "#c9a14a",
    background: "#fdf4e3",
    tier: "luxe",
    category: "Royal",
    family: "royal",
    badge: "Most Loved",
    layoutStyle: "parallax-sections",
    motionStyle: "gold-reveal",
    typographyStyle: "serif-regal",
  },
  {
    slug: "paris-romance",
    name: "Paris Romance",
    tagline: "Eiffel Tower dreams. Champagne kisses.",
    shortDescription: "A cinematic Parisian love story — French elegance, champagne blush tones, atmospheric sound, scroll-driven animations, and the romance of the City of Lights woven into every interaction.",
    couple: "Amélie & Étienne",
    location: "Paris, France",
    palette: ["#faf8f5", "#e8d4d0", "#c9a87c", "#2c2420"],
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=85",
    accent: "#d4a574",
    background: "#faf8f5",
    tier: "luxe",
    category: "Romantic",
    family: "romantic",
    badge: "Signature",
    layoutStyle: "magazine-editorial",
    motionStyle: "fade-crossover",
    typographyStyle: "script-french",
  },
  {
    slug: "tuscany-vineyard",
    name: "Tuscan Vineyard",
    tagline: "Amore under the Tuscan sun.",
    shortDescription: "Rolling hills, olive groves, terracotta warmth — an immersive Italian countryside experience with rich section transitions, atmospheric imagery, and rustic vineyard elegance.",
    couple: "Isabella & Marco",
    location: "Tuscany, Italy",
    palette: ["#faf6f1", "#c67b5c", "#6b7c5a", "#722f37"],
    image: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&w=1200&q=85",
    accent: "#c67b5c",
    background: "#faf6f1",
    tier: "luxe",
    category: "Rustic",
    family: "destination",
    layoutStyle: "split-screen",
    motionStyle: "warm-pan",
    typographyStyle: "serif-rustic",
  },
  {
    slug: "santorini-sunset",
    name: "Santorini Sunset",
    tagline: "Where the Aegean meets forever.",
    shortDescription: "Whitewashed domes, infinite blues, golden hour glow — a breathtaking Mediterranean destination invite with cinematic hero sequences and immersive coastal atmosphere.",
    couple: "Elena & Nikos",
    location: "Santorini, Greece",
    palette: ["#ffffff", "#4a90a4", "#1e3a5f", "#d4a574"],
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=85",
    accent: "#d4a574",
    background: "#ffffff",
    tier: "luxe",
    category: "Coastal",
    family: "destination",
    layoutStyle: "hero-cinematic",
    motionStyle: "wave-drift",
    typographyStyle: "sans-coastal",
  },
  {
    slug: "bollywood-sangeet",
    name: "Bollywood Night",
    tagline: "Dramatic. Vibrant. Unforgettable.",
    shortDescription: "Theatrical dark backgrounds, bold gradients, dramatic energy, and the spirit of a grand Bollywood celebration — with music, motion, and cinematic intensity.",
    couple: "Kiara & Ranvijay",
    location: "New Delhi",
    palette: ["#1a0a2e", "#ff6b35", "#ffd700", "#e91e63"],
    image: "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&w=1200&q=85",
    accent: "#ffd700",
    background: "#1a0a2e",
    tier: "luxe",
    category: "Dramatic",
    family: "festive",
    badge: "New",
    layoutStyle: "bold-stacked",
    motionStyle: "theatrical-burst",
    typographyStyle: "display-bold",
  },
  {
    slug: "enchanted-forest",
    name: "Enchanted Forest",
    tagline: "A fairytale woven in green and gold.",
    shortDescription: "Deep emerald canopies, firefly particles, enchanted typography, and mystical forest atmosphere — an immersive storybook experience for nature-loving couples.",
    couple: "Tara & Aditya",
    location: "Jim Corbett, Uttarakhand",
    palette: ["#0f1a0f", "#2d5a2d", "#c9a14a", "#f5f9f4"],
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=85",
    accent: "#c9a14a",
    background: "#0f1a0f",
    tier: "luxe",
    category: "Dramatic",
    family: "dramatic",
    layoutStyle: "immersive-fullscreen",
    motionStyle: "firefly-particle",
    typographyStyle: "serif-enchanted",
  },
  {
    slug: "cherry-blossom",
    name: "Cherry Blossom",
    tagline: "Petals falling like promises.",
    shortDescription: "Soft pinks, floating sakura petals, Japanese-inspired minimalism, and gentle spring warmth — a poetic invitation celebrating the fleeting beauty of love.",
    couple: "Sakura & Kenji",
    location: "Kyoto, Japan",
    palette: ["#fff5f7", "#f4a7b9", "#d4756e", "#2c1a1a"],
    image: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=1200&q=85",
    accent: "#d4756e",
    background: "#fff5f7",
    tier: "luxe",
    category: "Romantic",
    family: "floral",
    layoutStyle: "vertical-scroll",
    motionStyle: "petal-float",
    typographyStyle: "script-japanese",
  },

  // ═══════════════════════════════════════════
  //  BASIC — Elegant, clean, conversion-friendly
  // ═══════════════════════════════════════════
  {
    slug: "roses-luxury",
    name: "Classic Floral",
    tagline: "Hand-painted roses for a deeply romantic invitation.",
    shortDescription: "Cinematic floral composition with champagne gold typography and floating petals — delicate, emotional, and timeless.",
    couple: "Meera & Aarav",
    location: "Udaipur, Rajasthan",
    palette: ["#fff6f1", "#f2c8c1", "#c9a14a", "#4b1629"],
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85",
    accent: "#c9a14a",
    background: "#fff6f1",
    tier: "basic",
    category: "Floral",
    family: "floral",
    badge: "Bestseller",
  },
  {
    slug: "ivory-monogram",
    name: "Ivory Monogram",
    tagline: "Your initials. Timeless elegance.",
    shortDescription: "A sophisticated monogram-centered design with ivory backgrounds, gold lettering, and classical symmetry — refined and memorable.",
    couple: "Nisha & Aditya",
    location: "Bangalore",
    palette: ["#fdfcf8", "#d4c5a0", "#8b7355", "#1a1a1a"],
    image: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1200&q=85",
    accent: "#8b7355",
    background: "#fdfcf8",
    tier: "basic",
    category: "Editorial",
    family: "editorial",
  },
  {
    slug: "modern-gold",
    name: "Modern Gold",
    tagline: "Contemporary luxury. Bold simplicity.",
    shortDescription: "Clean geometric lines meet warm gold accents — a modern, confident invitation for couples who appreciate bold minimalism.",
    couple: "Riya & Sahil",
    location: "Pune",
    palette: ["#1a1a1a", "#c9a14a", "#ffffff", "#2a2a2a"],
    image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=85",
    accent: "#c9a14a",
    background: "#1a1a1a",
    tier: "basic",
    category: "Editorial",
    family: "editorial",
    badge: "Popular",
  },
  {
    slug: "pastel-garden",
    name: "Pastel Garden",
    tagline: "Soft hues. Gentle love.",
    shortDescription: "Watercolor pastels, soft lavender and mint tones, delicate garden illustrations — a gentle and joyful invitation for spring and summer weddings.",
    couple: "Kavya & Rohan",
    location: "Chandigarh",
    palette: ["#faf8fc", "#d4b8e8", "#a8d4a0", "#4a3a5c"],
    image: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=1200&q=85",
    accent: "#9b7ab8",
    background: "#faf8fc",
    tier: "basic",
    category: "Floral",
    family: "floral",
  },
  {
    slug: "sage-minimal",
    name: "Sage Minimal",
    tagline: "Less is more. Nature speaks.",
    shortDescription: "Muted sage greens, clean sans-serif typography, generous whitespace — a serene, nature-inspired invitation for minimalist couples.",
    couple: "Aisha & Vikram",
    location: "Dehradun",
    palette: ["#f7f9f5", "#7d9b76", "#4a5c48", "#2c3a2c"],
    image: "https://images.unsplash.com/photo-1464699908537-0954e50791ee?auto=format&fit=crop&w=1200&q=85",
    accent: "#7d9b76",
    background: "#f7f9f5",
    tier: "basic",
    category: "Romantic",
    family: "romantic",
  },
  {
    slug: "blush-romance",
    name: "Blush Romance",
    tagline: "Soft. Warm. Deeply personal.",
    shortDescription: "Warm blush tones, romantic script typography, and subtle floral borders — an intimate and feminine invitation that feels like a love letter.",
    couple: "Pooja & Arjun",
    location: "Lucknow",
    palette: ["#fdf5f3", "#e8b4a8", "#c97b6b", "#3a1a14"],
    image: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=85",
    accent: "#c97b6b",
    background: "#fdf5f3",
    tier: "basic",
    category: "Romantic",
    family: "romantic",
  },
  {
    slug: "heritage-cream",
    name: "Heritage Cream",
    tagline: "Tradition meets grace.",
    shortDescription: "Warm cream backgrounds, traditional border patterns, serif elegance — a dignified invitation that honors family heritage and cultural richness.",
    couple: "Sunita & Rajesh",
    location: "Jaipur",
    palette: ["#faf5e8", "#8b6b3a", "#c9a14a", "#2a1a0a"],
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=85",
    accent: "#8b6b3a",
    background: "#faf5e8",
    tier: "basic",
    category: "Royal",
    family: "traditional",
  },
  {
    slug: "sunset-mehendi",
    name: "Sunset Mehendi",
    tagline: "Henna patterns. Golden hour warmth.",
    shortDescription: "Intricate mehendi-inspired patterns, warm sunset oranges and deep reds — a vibrant Indian invitation celebrating traditional artistry.",
    couple: "Neha & Karan",
    location: "Jodhpur",
    palette: ["#fdf5ef", "#d4804a", "#8b4a2a", "#2a0f05"],
    image: "https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&w=1200&q=85",
    accent: "#d4804a",
    background: "#fdf5ef",
    tier: "basic",
    category: "Dramatic",
    family: "festive",
  },
  {
    slug: "minimal-elegant",
    name: "Clean Editorial",
    tagline: "Quiet luxury. Clean lines. Modern confidence.",
    shortDescription: "Editorial typography, magazine layout, and a sophisticated finish for couples who love understated design and visual clarity.",
    couple: "Isha & Arjun",
    location: "Mumbai",
    palette: ["#ffffff", "#efece6", "#b79862", "#111111"],
    image: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=85",
    accent: "#b79862",
    background: "#f7f6f2",
    tier: "basic",
    category: "Editorial",
    family: "editorial",
  },
  {
    slug: "soft-botanical",
    name: "Soft Botanical",
    tagline: "Nature's quiet poetry.",
    shortDescription: "Delicate botanical illustrations, soft greens and creams, organic layouts — an earthy yet elegant invitation for garden and outdoor weddings.",
    couple: "Ananya & Siddharth",
    location: "Coorg, Karnataka",
    palette: ["#f5f9f4", "#3d5a3d", "#7ba17b", "#2c3e2c"],
    image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=85",
    accent: "#5a8f5a",
    background: "#f5f9f4",
    tier: "basic",
    category: "Floral",
    family: "floral",
  },
  {
    slug: "traditional-red-gold",
    name: "Traditional Red & Gold",
    tagline: "Auspicious. Bold. Unforgettable.",
    shortDescription: "Rich crimson red with traditional gold motifs — a bold and auspicious Indian wedding invitation that commands attention and respect.",
    couple: "Priya & Rahul",
    location: "Delhi",
    palette: ["#fdf4e3", "#c9a14a", "#8b1a2b", "#1a0a05"],
    image: "https://images.unsplash.com/photo-1600850056064-a8b380df8395?auto=format&fit=crop&w=1200&q=85",
    accent: "#c9a14a",
    background: "#8b1a2b",
    tier: "basic",
    category: "Royal",
    family: "traditional",
    badge: "Classic",
  },
  {
    slug: "sky-blue-celebration",
    name: "Sky Blue Celebration",
    tagline: "Breezy. Joyful. Uplifting.",
    shortDescription: "Light sky blues, white clouds, and airy typography — a fresh, optimistic invitation perfect for daytime ceremonies and open-air celebrations.",
    couple: "Simran & Aryan",
    location: "Goa",
    palette: ["#f0f8ff", "#87ceeb", "#4a90a4", "#1a3a4a"],
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85",
    accent: "#4a90a4",
    background: "#f0f8ff",
    tier: "basic",
    category: "Coastal",
    family: "destination",
  },
  {
    slug: "pearl-white",
    name: "Pearl White",
    tagline: "Pure elegance. Nothing more.",
    shortDescription: "Pristine white, subtle pearl shimmer, and refined serif typography — the purest expression of wedding elegance for sophisticated couples.",
    couple: "Tanya & Nikhil",
    location: "Hyderabad",
    palette: ["#ffffff", "#f5f3ef", "#c9b896", "#1a1a1a"],
    image: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1200&q=85",
    accent: "#c9b896",
    background: "#ffffff",
    tier: "basic",
    category: "Editorial",
    family: "editorial",
  },
  {
    slug: "lavender-story",
    name: "Lavender Story",
    tagline: "Dreamy purple. Soft romance.",
    shortDescription: "Gentle lavender hues, romantic script, and soft gradient backgrounds — a dreamy and feminine invitation for couples who love color and warmth.",
    couple: "Diya & Manish",
    location: "Mysore",
    palette: ["#f8f5fd", "#9b7ab8", "#6b4a8a", "#2a1a3a"],
    image: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=1200&q=85",
    accent: "#9b7ab8",
    background: "#f8f5fd",
    tier: "basic",
    category: "Romantic",
    family: "romantic",
  },
  {
    slug: "minimal-monsoon",
    name: "Minimal Monsoon",
    tagline: "Rain-kissed love. Fresh beginnings.",
    shortDescription: "Muted greens, soft rain textures, and clean modern typography — a fresh, contemporary invitation inspired by monsoon romance.",
    couple: "Aditi & Varun",
    location: "Kerala",
    palette: ["#f4f8f4", "#4a7c5a", "#2d5a3d", "#1a2a1a"],
    image: "https://images.unsplash.com/photo-1464699908537-0954e50791ee?auto=format&fit=crop&w=1200&q=85",
    accent: "#4a7c5a",
    background: "#f4f8f4",
    tier: "basic",
    category: "Romantic",
    family: "romantic",
  },
  {
    slug: "boho-sundowner",
    name: "Boho Sundowner",
    tagline: "Golden hour. Barefoot elegance.",
    shortDescription: "Warm earthy tones, dried flower textures, and bohemian free-spirited energy — a sun-kissed invitation for Goa sundowners and outdoor celebrations.",
    couple: "Rhea & Kabir",
    location: "Goa",
    palette: ["#faf5ef", "#d4956b", "#8b6b4a", "#2d1810"],
    image: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=85",
    accent: "#d4956b",
    background: "#faf5ef",
    tier: "basic",
    category: "Rustic",
    family: "destination",
  },
  {
    slug: "beach-destination",
    name: "Beach Destination",
    tagline: "Sun, sand, and seashells.",
    shortDescription: "Navy blues, sandy golds, and coastal charm — a fresh seaside invitation for beach weddings and island celebrations.",
    couple: "Alia & Zayn",
    location: "Andaman Islands",
    palette: ["#f0f4f8", "#1e3a5f", "#4a90a4", "#d4a574"],
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85",
    accent: "#4a90a4",
    background: "#f0f4f8",
    tier: "basic",
    category: "Coastal",
    family: "destination",
  },
];
