export interface SampleStory {
  id: string;
  themeSlug: string;
  cardTeaser: string;
  cardCTA: string;
  heroTitle: string;
  heroSubtitle: string;
  heroImage: string;
  heroImagePosition?: string;
  cardImage?: string;
  cardImagePosition?: string;
  cardImageFit?: "cover" | "contain";
  groomName: string;
  brideName: string;
  groomFullName?: string;
  brideFullName?: string;
  city: string;
  venue: string;
  venueAddress?: string;
  welcomeNote: string;
  ourStoryTitle: string;
  howWeMet: string;
  littleThings: string;
  proposalTitle: string;
  proposalStory: string;
  groomFamily?: string;
  brideFamily?: string;
  galleryImages: string[];
  galleryImagePositions?: string[];
  events: Array<{
    name: string;
    date: string;
    time: string;
    venue: string;
    description?: string;
  }>;
  dressCode?: string;
  closingNote: string;
  rsvpText: string;
}

function make4k(url: string) {
  return url.replace(/w=\d+/g, "w=3840").replace(/q=\d+/g, "q=92");
}

const PREMIUM_4K = {
  palace: make4k("https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=1200&q=90"),
  nightSky: make4k("https://images.unsplash.com/photo-1507400492013-162706c8c05e?auto=format&fit=crop&w=1200&q=90"),
  tuscany: make4k("https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&w=1200&q=85"),
  santorini: make4k("https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=85"),
  festive: make4k("https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?auto=format&fit=crop&w=1200&q=85"),
  forest: make4k("https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=85"),
  blossom: make4k("https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=1200&q=85"),
  floral: make4k("https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85"),
  stationery: make4k("https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1200&q=85"),
  editorial: make4k("https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=85"),
  pastel: make4k("https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=1200&q=85"),
  monsoon: make4k("https://images.unsplash.com/photo-1464699908537-0954e50791ee?auto=format&fit=crop&w=1200&q=85"),
  ballroom: make4k("https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=85"),
  quietLuxury: make4k("https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=85"),
  botanical: make4k("https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=85"),
  redGold: make4k("https://images.unsplash.com/photo-1600850056064-a8b380df8395?auto=format&fit=crop&w=1200&q=85"),
  seaside: make4k("https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85"),
  boho: make4k("https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=85"),
};

export const SAMPLE_STORIES: SampleStory[] = [
  {
    id: "sidharth-kiara",
    themeSlug: "palace-heirloom",
    cardTeaser: "From Shershaah's quiet chemistry to a desert palace lit in gold, their forever arrived like a film frame made real.",
    cardCTA: "Step into their royal celebration",
    heroTitle: "Sidharth Malhotra & Kiara Advani",
    heroSubtitle: "A desert palace, a moonlit varmala, and a love story written with grace",
    heroImage: "/story-assets/sidharth-kiara/sidharth-kiara-card-hd.jpg",
    heroImagePosition: "center 38%",
    cardImage: "/story-assets/sidharth-kiara/sidharth-kiara-card-hd.jpg",
    cardImagePosition: "center 40%",
    cardImageFit: "contain",
    groomName: "Sidharth",
    brideName: "Kiara",
    groomFullName: "Sidharth Malhotra",
    brideFullName: "Kiara Advani",
    city: "Jaisalmer",
    venue: "Suryagarh Palace, Jaisalmer",
    venueAddress: "Sam Road, Jaisalmer, Rajasthan 345001",
    welcomeNote: "With the dunes of Jaisalmer glowing around us and our families by our side, we invite you to celebrate a love that moved from the screen into real life. Join us for an evening of warmth, music, and a promise that feels timeless.",
    ourStoryTitle: "When Reel Love Became Real",
    howWeMet: "They met while filming Shershaah, a story already steeped in love and longing. What began as admiration deepened slowly, quietly, and beautifully, until the world watching from afar realized the tenderness on screen was no act at all.",
    littleThings: "Sidharth treasures Kiara's lightness and the way joy follows her into every room. Kiara loves Sidharth's steadiness, his gentleness, and the calm confidence with which he shows up for love.",
    proposalTitle: "He Asked for Forever",
    proposalStory: "Away from the noise, in a moment known only to the two of them, Sidharth asked Kiara to build a life with him. It was intimate, certain, and entirely their own. Some promises do not need spectacle when the feeling has already said everything.",
    groomFamily: "Son of Sunil & Rimma Malhotra",
    brideFamily: "Daughter of Jagdeep & Genevieve Advani",
    galleryImages: [
      PREMIUM_4K.palace,
      PREMIUM_4K.ballroom,
      PREMIUM_4K.redGold,
      PREMIUM_4K.boho,
      PREMIUM_4K.nightSky,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Desert Revelry",
        date: "Sunday, 5th February 2023",
        time: "4:00 PM onwards",
        venue: "Suryagarh Palace, Jaisalmer",
        description: "An evening of mehendi, music, candlelight, and golden desert glamour.",
      },
      {
        name: "Wedding Ceremony",
        date: "Tuesday, 7th February 2023",
        time: "7:00 PM",
        venue: "Suryagarh Palace, Jaisalmer",
        description: "A moonlit union in the golden city.",
      },
      {
        name: "Mumbai Reception",
        date: "Sunday, 12th February 2023",
        time: "8:00 PM",
        venue: "The St. Regis Mumbai",
        description: "A luminous celebration with family, friends, and the film fraternity.",
      },
    ],
    dressCode: "Royal Indian formal in jewel, gold, and ivory tones.",
    closingNote: "Your presence would mean the world to us as we begin this beautiful chapter. Come celebrate in Jaisalmer, where our forever begins.",
    rsvpText: "Kindly grace us with your presence",
  },
  {
    id: "vicky-katrina",
    themeSlug: "paris-romance",
    cardTeaser: "Rose petals, old stone walls, and a love they guarded quietly until the world saw it bloom.",
    cardCTA: "Enter their Fort Barwara romance",
    heroTitle: "Vicky Kaushal & Katrina Kaif",
    heroSubtitle: "Only love and gratitude, wrapped in the warm blush of Fort Barwara",
    heroImage: "/story-assets/vicky-katrina/vicky-katrina-1.jpg",
    heroImagePosition: "center 26%",
    cardImagePosition: "center 24%",
    groomName: "Vicky",
    brideName: "Katrina",
    groomFullName: "Vicky Kaushal",
    brideFullName: "Katrina Kaif",
    city: "Sawai Madhopur",
    venue: "Six Senses Fort Barwara",
    venueAddress: "Chauth Ka Barwara, Sawai Madhopur, Rajasthan 322702",
    welcomeNote: "With hearts full of gratitude and a fort wrapped in candlelight around us, we invite you to witness a celebration that felt deeply personal from the very first moment. Join us in Rajasthan as we begin our forever beneath winter skies and old-world stone.",
    ourStoryTitle: "A Quiet Love in Full Bloom",
    howWeMet: "What began in the quiet corners of Mumbai's film world slowly became something deeply anchored and beautifully certain. Their love was never loud for the world; it was built in glances, trust, warmth, and the rare comfort of finding home in another person.",
    littleThings: "Vicky loves Katrina's grace and the sincerity she brings to every room. Katrina treasures Vicky's open-hearted warmth and the way he makes joy feel effortless and safe.",
    proposalTitle: "A Promise Kept Close",
    proposalStory: "Before the celebrations and the headlines, there was a private yes between two people who knew exactly what they had found. Their wedding carried that same feeling into every ritual: intimate, tender, and overflowing with love.",
    groomFamily: "Son of Sham & Veena Kaushal",
    brideFamily: "Daughter of Mohammed Kaif & Suzanne Turquotte",
    galleryImages: [
      PREMIUM_4K.floral,
      PREMIUM_4K.palace,
      PREMIUM_4K.quietLuxury,
      PREMIUM_4K.boho,
      PREMIUM_4K.redGold,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Mehendi & Celebration Evening",
        date: "Wednesday, 8th December 2021",
        time: "4:00 PM onwards",
        venue: "Six Senses Fort Barwara",
        description: "Rose petals, music, and the warmth of both families gathered together.",
      },
      {
        name: "Wedding Ceremony",
        date: "Thursday, 9th December 2021",
        time: "3:30 PM",
        venue: "Six Senses Fort Barwara",
        description: "A sacred ceremony set against fort walls, winter light, and timeless vows.",
      },
    ],
    dressCode: "Romantic Indian formal in blush, rose, champagne, and ivory.",
    closingNote: "Thank you for carrying our story with so much love. We cannot wait to celebrate this chapter with you.",
    rsvpText: "Join us in Fort Barwara",
  },
  {
    id: "virat-anushka",
    themeSlug: "tuscany-vineyard",
    cardTeaser: "From a chance commercial to a Tuscan wedding, their story became a collective memory for an entire generation.",
    cardCTA: "Step into their Tuscany",
    heroTitle: "Virat Weds Anushka",
    heroSubtitle: "Under the Tuscan sun, where India's most beloved couple said forever",
    heroImage: "/story-assets/virat-anushka/virat-anushka-1.jpg",
    heroImagePosition: "center 22%",
    cardImagePosition: "center 24%",
    groomName: "Virat",
    brideName: "Anushka",
    groomFullName: "Virat Kohli",
    brideFullName: "Anushka Sharma",
    city: "Tuscany, Italy",
    venue: "Borgo Finocchieto, Tuscany",
    venueAddress: "Buonconvento, Siena, Tuscany, Italy",
    welcomeNote: "Surrounded by rolling hills and winter light in Tuscany, we celebrated the quiet beginning of forever. We are grateful for every person who has cheered for our love, and now invite you to share in the most intimate chapter of our story.",
    ourStoryTitle: "A Love the World Cherished",
    howWeMet: "They first met in 2013 while filming a commercial. A cricketer at the height of his powers and an actress carrying her own luminous world, they found connection in a setting that seemed ordinary until it changed everything.",
    littleThings: "Virat loves how Anushka grounds him with grace and clarity. Anushka loves Virat's devotion, his intensity, and the warmth behind his strength. Together they built a love rooted in faith, family, and deep companionship.",
    proposalTitle: "The Quiet Yes That Moved Millions",
    proposalStory: "Long before Tuscany became the setting the world remembers, their forever had already been chosen in private. When the wedding news finally arrived, it felt less like a surprise and more like the world collectively exhaling into joy.",
    groomFamily: "Son of Late Prem Kohli & Saroj Kohli",
    brideFamily: "Daughter of Col. Ajay Kumar Sharma & Ashima Sharma",
    galleryImages: [
      PREMIUM_4K.tuscany,
      PREMIUM_4K.botanical,
      PREMIUM_4K.boho,
      PREMIUM_4K.blossom,
      PREMIUM_4K.monsoon,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Wedding Ceremony",
        date: "Monday, 11th December 2017",
        time: "5:00 PM",
        venue: "Borgo Finocchieto, Tuscany",
        description: "An intimate ceremony among family and the closest of friends.",
      },
      {
        name: "Delhi Reception",
        date: "Thursday, 21st December 2017",
        time: "7:30 PM",
        venue: "Taj Diplomatic Enclave, New Delhi",
        description: "A celebration in the capital with family, friends, and well-wishers.",
      },
      {
        name: "Mumbai Reception",
        date: "Tuesday, 26th December 2017",
        time: "7:30 PM",
        venue: "The St. Regis Mumbai",
        description: "A luminous Mumbai evening shared with cricket and cinema's inner circles.",
      },
    ],
    dressCode: "Elegant Indian formal with rich ivory, blush, and classic Sabyasachi detailing.",
    closingNote: "Thank you for being part of our journey. Your love and blessings have always meant the world to us.",
    rsvpText: "Join us in Tuscany and in our hearts",
  },
  {
    id: "harry-meghan",
    themeSlug: "santorini-sunset",
    cardTeaser: "A royal procession, a sunlit kiss, and a wedding that felt both historic and unexpectedly intimate.",
    cardCTA: "Enter their Windsor day",
    heroTitle: "Prince Harry & Meghan Markle",
    heroSubtitle: "A spring wedding at Windsor, where tradition met modern grace",
    heroImage: "/story-assets/harry-meghan/harry-meghan-4.jpg",
    heroImagePosition: "center 22%",
    cardImage: "/story-assets/harry-meghan/harry-meghan-5.jpg",
    cardImagePosition: "center 32%",
    cardImageFit: "contain",
    groomName: "Harry",
    brideName: "Meghan",
    groomFullName: "Prince Harry, Duke of Sussex",
    brideFullName: "Meghan Markle",
    city: "Windsor",
    venue: "St George's Chapel, Windsor Castle",
    venueAddress: "Windsor SL4 1NJ, United Kingdom",
    welcomeNote: "In the heart of Windsor, beneath vaulted stone and spring light, we invite you to witness a celebration of love that honors tradition while opening itself to a new kind of grace. Join us for a day of vows, music, bells, and a carriage procession that the world will remember.",
    ourStoryTitle: "A Modern Fairy Tale",
    howWeMet: "They were introduced on a blind date in London in 2016. What followed was a swift and certain love, built across continents, private dinners, and a deep sense of recognition that they had found in each other something both grounding and extraordinary.",
    littleThings: "Harry loves Meghan's poise, warmth, and fearless compassion. Meghan treasures Harry's humor, tenderness, and the devotion with which he protects the life they are building together.",
    proposalTitle: "The Night It Became Forever",
    proposalStory: "In the quiet comfort of Nottingham Cottage, over a simple evening in, Harry proposed. It was unguarded and heartfelt, the kind of moment that feels unforgettable precisely because it is filled with sincerity rather than spectacle.",
    groomFamily: "Son of King Charles III & Diana, Princess of Wales",
    brideFamily: "Daughter of Thomas Markle Sr. & Doria Ragland",
    galleryImages: [
      PREMIUM_4K.botanical,
      PREMIUM_4K.seaside,
      PREMIUM_4K.palace,
      PREMIUM_4K.floral,
      PREMIUM_4K.stationery,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Wedding Service",
        date: "Saturday, 19th May 2018",
        time: "12:00 PM",
        venue: "St George's Chapel, Windsor Castle",
        description: "A royal wedding service with gospel, vows, and ringing chapel bells.",
      },
      {
        name: "Carriage Procession",
        date: "Saturday, 19th May 2018",
        time: "1:00 PM",
        venue: "Windsor Castle Grounds",
        description: "A sunlit procession through Windsor, shared with the world.",
      },
      {
        name: "Evening Reception",
        date: "Saturday, 19th May 2018",
        time: "7:00 PM",
        venue: "Frogmore House",
        description: "An intimate evening reception for family and close friends.",
      },
    ],
    dressCode: "Classic day formal, refined tailoring, and understated elegance.",
    closingNote: "Your presence would complete this joyous day as we begin the next chapter of our lives together.",
    rsvpText: "Join us in Windsor",
  },
  {
    id: "priyanka-nick",
    themeSlug: "bollywood-sangeet",
    cardTeaser: "Two continents, two ceremonies, and one of the most cinematic unions modern celebrity culture has ever seen.",
    cardCTA: "Enter their royal world",
    heroTitle: "Priyanka Chopra & Nick Jonas",
    heroSubtitle: "When Bollywood met Hollywood at Umaid Bhawan Palace",
    heroImage: "/story-assets/priyanka-nick/priyanka-nick-2.png",
    heroImagePosition: "center 20%",
    cardImagePosition: "center 22%",
    groomName: "Nick",
    brideName: "Priyanka",
    groomFullName: "Nicholas Jerry Jonas",
    brideFullName: "Priyanka Chopra Jonas",
    city: "Jodhpur",
    venue: "Umaid Bhawan Palace, Jodhpur",
    venueAddress: "Circuit House Road, Cantt Area, Jodhpur, Rajasthan 342006",
    welcomeNote: "Two worlds, two cultures, and one extraordinary love. Join us at Umaid Bhawan Palace as we celebrate a union that honors both our heritages with music, ritual, glamour, and joy.",
    ourStoryTitle: "When Two Worlds Became One",
    howWeMet: "Their story began with a message, bloomed through red carpets and long-distance flights, and soon became one of the most talked-about romances in the world. Yet beneath the headlines was something far simpler: two people who recognized home in each other.",
    littleThings: "Nick loves how Priyanka carries India with her in everything she does. Priyanka loves how fully Nick shows up for love, family, and every room they walk into together.",
    proposalTitle: "A Yes Heard Around the World",
    proposalStory: "On Priyanka's birthday in London, Nick proposed with an iconic ring and a certainty that felt larger than the moment itself. Their answer to that yes became a wedding that was as grand as it was deeply personal.",
    groomFamily: "Son of Paul Kevin Jonas Sr. & Denise Miller Jonas",
    brideFamily: "Daughter of Dr. Ashok Chopra & Dr. Madhu Chopra",
    galleryImages: [
      PREMIUM_4K.ballroom,
      PREMIUM_4K.palace,
      PREMIUM_4K.redGold,
      PREMIUM_4K.festive,
      PREMIUM_4K.quietLuxury,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Mehendi Ceremony",
        date: "Friday, 30th November 2018",
        time: "4:00 PM",
        venue: "Umaid Bhawan Palace Gardens",
        description: "A vibrant celebration of Indian tradition, music, and color.",
      },
      {
        name: "Christian Wedding Ceremony",
        date: "Saturday, 1st December 2018",
        time: "6:00 PM",
        venue: "Umaid Bhawan Palace",
        description: "A Western ceremony inside a royal Indian setting.",
      },
      {
        name: "Hindu Wedding Ceremony",
        date: "Sunday, 2nd December 2018",
        time: "6:00 PM",
        venue: "Umaid Bhawan Palace",
        description: "A traditional Hindu celebration of union and blessing.",
      },
    ],
    dressCode: "Bollywood royalty with space for both Indian opulence and black-tie elegance.",
    closingNote: "Two cultures, one love, and a celebration we will remember forever. Your presence would mean the world to us.",
    rsvpText: "Join us in Jodhpur",
  },
  {
    id: "ranbir-alia",
    themeSlug: "roses-luxury",
    cardTeaser: "Sunlit ivory, jasmine strings, and a balcony wedding that felt like the softest kind of luxury.",
    cardCTA: "Enter their Mumbai day",
    heroTitle: "Ranbir Kapoor & Alia Bhatt",
    heroSubtitle: "An intimate balcony wedding wrapped in ivory, gold, and family",
    heroImage: "/story-assets/ranbir-alia/ranbir-alia-5.jpg",
    heroImagePosition: "center 24%",
    cardImagePosition: "center 24%",
    groomName: "Ranbir",
    brideName: "Alia",
    groomFullName: "Ranbir Kapoor",
    brideFullName: "Alia Bhatt",
    city: "Mumbai",
    venue: "Vastu, Pali Hill",
    venueAddress: "Pali Hill, Bandra West, Mumbai, Maharashtra",
    welcomeNote: "In the home that has witnessed our happiest ordinary moments, we invite you to celebrate a day built on closeness, light, and the people who know us best. Join us in Mumbai for a wedding that feels intimate, luminous, and deeply ours.",
    ourStoryTitle: "A Love Lit by Familiar Light",
    howWeMet: "They came together while working on Brahmastra, but what followed stretched far beyond a film set. Their bond grew through years of friendship, family, work, and the quiet understanding that some loves deepen most beautifully away from noise.",
    littleThings: "Ranbir loves Alia's instinctive joy and the sincerity she brings to every gesture. Alia loves Ranbir's calm, his protective warmth, and the ease with which he makes her feel at home.",
    proposalTitle: "The Yes Before the Ceremony",
    proposalStory: "Their wedding was intimate by design, but no less grand in feeling. Every detail pointed inward toward memory, family, and the life already taking shape between them long before the first vow was spoken.",
    groomFamily: "Son of Rishi Kapoor & Neetu Kapoor",
    brideFamily: "Daughter of Mahesh Bhatt & Soni Razdan",
    galleryImages: [
      PREMIUM_4K.floral,
      PREMIUM_4K.botanical,
      PREMIUM_4K.stationery,
      PREMIUM_4K.quietLuxury,
      PREMIUM_4K.pastel,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Mehendi & Haldi",
        date: "Wednesday, 13th April 2022",
        time: "2:00 PM",
        venue: "Vastu, Pali Hill",
        description: "An intimate afternoon of ritual, laughter, and family blessings.",
      },
      {
        name: "Wedding Ceremony",
        date: "Thursday, 14th April 2022",
        time: "2:00 PM",
        venue: "Vastu, Pali Hill",
        description: "A private ceremony held in the couple's favorite corner of home.",
      },
    ],
    dressCode: "Soft ivory, antique gold, and heirloom elegance.",
    closingNote: "Thank you for being part of this tender chapter. We would be honored to celebrate it with you.",
    rsvpText: "Join us in Mumbai",
  },
  {
    id: "kl-athiya",
    themeSlug: "ivory-monogram",
    cardTeaser: "An understated wedding in Khandala, bathed in sunlight, jasmine, and the ease of a love grown quietly over time.",
    cardCTA: "Discover their Khandala day",
    heroTitle: "KL Rahul & Athiya Shetty",
    heroSubtitle: "A softly lit celebration in Khandala, made radiant by stillness and grace",
    heroImage: "/story-assets/kl-athiya/kl-athiya-1.jpg",
    heroImagePosition: "center 24%",
    cardImage: "/story-assets/kl-athiya/kl-athiya-3.jpg",
    cardImagePosition: "center 32%",
    cardImageFit: "contain",
    groomName: "Rahul",
    brideName: "Athiya",
    groomFullName: "Kannanur Lokesh Rahul",
    brideFullName: "Athiya Shetty",
    city: "Khandala",
    venue: "Jahan, Khandala",
    venueAddress: "Suniel Shetty's farmhouse, Khandala, Maharashtra",
    welcomeNote: "With the hills of Khandala around us and our closest people gathered in peace, we invite you to celebrate a love that has always preferred sincerity over spectacle. Join us for a day of jasmine, sunlight, music, and timeless promises.",
    ourStoryTitle: "A Love Built with Ease",
    howWeMet: "Their relationship unfolded gently and without hurry, grounded in friendship, trust, and the quiet certainty of two people who never needed to perform their love for the world to know it was real.",
    littleThings: "Rahul loves Athiya's softness and the serenity she carries into every moment. Athiya loves Rahul's composure, his warmth, and the deep steadiness he brings into the life they share.",
    proposalTitle: "The Kind of Yes That Feels Like Peace",
    proposalStory: "Their wedding carried the same mood as their relationship: refined, intimate, and deeply unforced. Every detail felt touched by calm, the kind of calm that only arrives when love has already made itself home.",
    groomFamily: "Son of K. N. Lokesh & Rajeshwari Rahul",
    brideFamily: "Daughter of Suniel & Mana Shetty",
    galleryImages: [
      PREMIUM_4K.botanical,
      PREMIUM_4K.monsoon,
      PREMIUM_4K.quietLuxury,
      PREMIUM_4K.stationery,
      PREMIUM_4K.floral,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Sangeet Evening",
        date: "Sunday, 22nd January 2023",
        time: "7:00 PM",
        venue: "Jahan, Khandala",
        description: "A night of music, dancing, and families gathered under the stars.",
      },
      {
        name: "Wedding Ceremony",
        date: "Monday, 23rd January 2023",
        time: "4:00 PM",
        venue: "Jahan, Khandala",
        description: "An intimate wedding ceremony framed by florals, sunlight, and the hills.",
      },
    ],
    dressCode: "Ivory, muted gold, and refined day-wedding elegance.",
    closingNote: "Your love and blessings would make this celebration even more meaningful. We cannot wait to share it with you.",
    rsvpText: "Join us in Khandala",
  },
  {
    id: "shahid-mira",
    themeSlug: "blush-romance",
    cardTeaser: "Rose-tinted lehengas, handwritten vows of faith, and a wedding that felt personal in the most beautiful way.",
    cardCTA: "Step into their Delhi celebration",
    heroTitle: "Shahid Kapoor & Mira Rajput",
    heroSubtitle: "A blush-toned wedding in Delhi, intimate at heart and luminous in memory",
    heroImage: "/story-assets/shahid-mira/shahid-mira-3.jpg",
    heroImagePosition: "center 18%",
    cardImage: "/story-assets/shahid-mira/shahid-mira-card-hd.jpg",
    cardImagePosition: "center 34%",
    cardImageFit: "contain",
    groomName: "Shahid",
    brideName: "Mira",
    groomFullName: "Shahid Kapoor",
    brideFullName: "Mira Rajput",
    city: "Delhi",
    venue: "Shivinder Singh's Farmhouse, Rajokri",
    venueAddress: "Rajokri, New Delhi",
    welcomeNote: "With our families close and our celebrations wrapped in softness, music, and gratitude, we invite you to be part of a wedding that honors love in its most personal form. Join us in Delhi as we begin our forever.",
    ourStoryTitle: "A Love Chosen with Intention",
    howWeMet: "They were introduced through family and faith, and what followed was an old-fashioned love story in the most elegant sense. Their connection was rooted in shared values, quiet trust, and the feeling that they had met each other at exactly the right moment.",
    littleThings: "Shahid loves Mira's warmth, clarity, and the way she brings lightness into every gathering. Mira loves Shahid's sensitivity, his intensity, and the devotion behind the way he loves.",
    proposalTitle: "A Gentle Turning of Fate",
    proposalStory: "Not every great love story begins with spectacle. Some begin with a family introduction, a conversation that lingers, and a certainty that grows stronger with each passing moment. Their wedding held that same gentle conviction.",
    groomFamily: "Son of Pankaj Kapur & Neelima Azeem",
    brideFamily: "Daughter of Vikramaditya & Bela Rajput",
    galleryImages: [
      PREMIUM_4K.floral,
      PREMIUM_4K.botanical,
      PREMIUM_4K.quietLuxury,
      PREMIUM_4K.ballroom,
      PREMIUM_4K.stationery,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Sangeet & Haldi",
        date: "Monday, 6th July 2015",
        time: "7:00 PM",
        venue: "The Trident, Gurugram",
        description: "A family evening of music, blessings, and celebration.",
      },
      {
        name: "Wedding Ceremony",
        date: "Tuesday, 7th July 2015",
        time: "11:00 AM",
        venue: "Shivinder Singh's Farmhouse, Rajokri",
        description: "An intimate ceremony attended by close family and cherished friends.",
      },
      {
        name: "Delhi Reception",
        date: "Tuesday, 7th July 2015",
        time: "8:00 PM",
        venue: "The Oberoi, Gurugram",
        description: "An evening reception in classic black-tie style.",
      },
    ],
    dressCode: "Blush, ivory, and refined Indian formal with a romantic edge.",
    closingNote: "We would be honored to celebrate this beautiful new chapter with you. Thank you for your love and blessings.",
    rsvpText: "Join us in Delhi",
  },
  {
    id: "yuvraj-hazel",
    themeSlug: "heritage-cream",
    cardTeaser: "From an intimate gurudwara ceremony to a second set of vows by the sea, their wedding carried both devotion and celebration.",
    cardCTA: "Walk through their wedding week",
    heroTitle: "Yuvraj Singh & Hazel Keech",
    heroSubtitle: "A wedding of prayer, celebration, and a second promise by the sea",
    heroImage: "/story-assets/yuvraj-hazel/yuvraj-hazel-1.jpg",
    heroImagePosition: "center 36%",
    cardImage: "/story-assets/yuvraj-hazel/yuvraj-hazel-1.jpg",
    cardImagePosition: "center 36%",
    cardImageFit: "contain",
    groomName: "Yuvraj",
    brideName: "Hazel",
    groomFullName: "Yuvraj Singh",
    brideFullName: "Hazel Keech",
    city: "Fatehgarh Sahib & Goa",
    venue: "Dera of Baba Ram Singh Ji, Fatehgarh Sahib",
    venueAddress: "Fatehgarh Sahib district, Punjab",
    welcomeNote: "With prayer at the center of our celebrations and joy woven through every gathering, we invite you to join us for a wedding week that moves from Punjab to Goa, from quiet blessing to vibrant celebration.",
    ourStoryTitle: "Love Across Two Ceremonies",
    howWeMet: "Their story unfolded with patience, persistence, and affection that only deepened over time. When the day finally arrived, their wedding reflected both the sacredness of union and the exuberance of a celebration long awaited.",
    littleThings: "Yuvraj loves Hazel's spark, her softness, and the joy she carries effortlessly. Hazel loves Yuvraj's fierce heart, his humor, and the tenderness behind his strength.",
    proposalTitle: "A Celebration That Kept Growing",
    proposalStory: "Their wedding did not belong to one room or one ritual. It unfolded in chapters, each one adding a new kind of beauty: devotion in Punjab, festivity in Goa, and the feeling of a love ready to be celebrated with the whole world.",
    groomFamily: "Son of Yograj Singh & Shabnam Singh",
    galleryImages: [
      PREMIUM_4K.palace,
      PREMIUM_4K.redGold,
      PREMIUM_4K.boho,
      PREMIUM_4K.seaside,
      PREMIUM_4K.botanical,
    ],
    galleryImagePositions: ["center center", "center center", "center center", "center center", "center center"],
    events: [
      {
        name: "Sikh Wedding Ceremony",
        date: "Wednesday, 30th November 2016",
        time: "11:00 AM",
        venue: "Dera of Baba Ram Singh Ji, Fatehgarh Sahib",
        description: "A traditional Anand Karaj surrounded by family and blessings.",
      },
      {
        name: "Goa Pheras",
        date: "Friday, 2nd December 2016",
        time: "6:00 PM",
        venue: "Teso Waterfront, Siolim, Goa",
        description: "A seaside Hindu ceremony lit by sunset and celebration.",
      },
      {
        name: "Delhi Reception",
        date: "Wednesday, 7th December 2016",
        time: "8:00 PM",
        venue: "Hotel Maurya, New Delhi",
        description: "A grand reception to conclude a wedding week full of heart.",
      },
    ],
    dressCode: "Heritage Indian formal with room for celebration, color, and sparkle.",
    closingNote: "Thank you for being part of this beautiful journey. We cannot wait to celebrate it with you.",
    rsvpText: "Join us from Punjab to Goa",
  },
  {
    id: "sunset-mehendi",
    themeSlug: "sunset-mehendi",
    cardTeaser: "A sunset mehendi wrapped in marigold light, temple bells, and the quiet romance of Shiva-Parvati blessing the evening.",
    cardCTA: "Reserve this sunset celebration",
    heroTitle: "Shivansh & Aarohi",
    heroSubtitle: "A mehendi evening blessed by Shiva and Parvati, glowing with devotion and golden-hour romance",
    heroImage: "/story-assets/sunset-mehendi/shiva-parvati-cover.png",
    heroImagePosition: "center 18%",
    cardImagePosition: "center 20%",
    groomName: "Shivansh",
    brideName: "Aarohi",
    city: "Jodhpur",
    venue: "Sunset Courtyard, Jodhpur",
    venueAddress: "Jodhpur, Rajasthan",
    welcomeNote: "As the sky turns saffron and marigold light settles across the courtyard, we invite you to join us for a mehendi evening shaped by devotion, music, and the blessing of Shiva and Parvati. It will be intimate, luminous, and full of heart.",
    ourStoryTitle: "Where Devotion Meets Celebration",
    howWeMet: "Our story began gently, with the kind of ease that feels fated from the very beginning. What drew us together was not noise but recognition, and the beautiful certainty that love can feel both grounding and sacred at once.",
    littleThings: "Temple bells, marigold garlands, hand-drawn henna, sandalwood, and the blessing of Shiva and Parvati create an evening that feels divine, romantic, and deeply refined.",
    proposalTitle: "A Sacred Mood, Beautifully Told",
    proposalStory: "Before the music and the mehendi came a promise held close to the heart. This celebration carries that promise forward with warmth, beauty, and a sense of grace that feels timeless.",
    galleryImages: [
      "/story-assets/sunset-mehendi/shiva-parvati-3.jpg",
      "/story-assets/sunset-mehendi/shiva-parvati-2.jpg",
      PREMIUM_4K.redGold,
      PREMIUM_4K.boho,
      PREMIUM_4K.palace,
    ],
    galleryImagePositions: ["center 22%", "center 24%", "center center", "center center", "center center"],
    events: [
      {
        name: "Mehendi Ritual",
        date: "2026-02-13",
        time: "5:30 PM",
        venue: "Sunset Courtyard, Jodhpur",
        description: "Henna, shehnai, petals, and golden-hour blessings.",
      },
      {
        name: "Sangeet Under the Lamps",
        date: "2026-02-13",
        time: "8:00 PM",
        venue: "Sunset Courtyard, Jodhpur",
        description: "A romantic evening of music, dance, and divine atmosphere.",
      },
    ],
    dressCode: "Saffron, vermilion, ivory, and festive Indian couture with sacred detailing.",
    closingNote: "May this evening be filled with beauty, blessing, and the warmth of everyone we hold dear.",
    rsvpText: "Join us for mehendi at sunset",
  },
];

export function getStoryBySlug(themeSlug: string): SampleStory | undefined {
  return SAMPLE_STORIES.find((story) => story.themeSlug === themeSlug);
}

export function getStoryPreviewImage(themeSlug: string, fallbackImage: string): string {
  const story = getStoryBySlug(themeSlug);
  return story?.cardImage || story?.heroImage || fallbackImage;
}

export function getStoryPreviewPosition(themeSlug: string): string {
  const story = getStoryBySlug(themeSlug);
  return story?.cardImagePosition || story?.heroImagePosition || "center center";
}

export function getStoryPreviewFit(themeSlug: string): "cover" | "contain" {
  const story = getStoryBySlug(themeSlug);
  if (!story) {
    return "cover";
  }

  return story.cardImageFit || "contain";
}

export function hasStory(themeSlug: string): boolean {
  return SAMPLE_STORIES.some((story) => story.themeSlug === themeSlug);
}
